### ISSUE TITLE
Error on @frontend alias

### ISSUE THREAD

**Issue by macklus** [c006/yii2-paypal-ipn#1]
Hi:

I install your module on a Yii2 basic app, and it crash beause @frontend is not defined (it only are on Yii2 advanced app).

I thinks is better replace line 64 @frontend by @runtime, who is present on all apps

thanks in advance

**Comment by c006** [comment]
Hi, yes it was built for the advanced version.

@frontend => @web

That should work.

Regards,
Jon

**Comment by macklus** [comment]
Hi:

So far this is a log file, it should be on runtime directory, and, more important, @runtime works on any Yii app, so, please, change it so works for everione without manually modify files (that can be overwriten on future updates)

thanks in advance

**Comment by c006** [comment]
Excellent point, I will change with next round of updates.
